In [7]:
cd("/home/jzhang/gis_data/jzhang/MyAI")
using Pkg; 
import Pkg; 
Pkg.activate(".")

  Activating project at `/media/jzhang/gis_data/jzhang/MyAI`


In [9]:
#Pkg.add("CUDA")
Pkg.add("BenchmarkTools")
Pkg.add("Plots")
Pkg.add("DataFrames")
Pkg.add("CSV")
Pkg.add("MLJ")
Pkg.add("MLJModels")
Pkg.add("TextAnalysis")

##Pkg.add("PyCall")
Pkg.add("Chain")
Pkg.add("Pipe")
Pkg.add("Compose")
Pkg.add("Gadfly")
Pkg.add("Query")
Pkg.add("Statistics")
Pkg.add("StatsBase")
Pkg.add("StableRNGs")
Pkg.add("PrettyPrinting")

   Resolving package versions...


LoadError: Unsatisfiable requirements detected for package GPUCompiler [61eb1bfa]:
 GPUCompiler [61eb1bfa] log:
 ├─possible versions are: 0.1.0 - 2.0.1 or uninstalled
 ├─restricted by compatibility requirements with CUDA [052768ef] to versions: 0.24.0 - 0.27.8
 │ └─CUDA [052768ef] log:
 │   ├─possible versions are: 0.1.0 - 6.2.1 or uninstalled
 │   ├─restricted to versions * by project [03412277], leaving only versions: 0.1.0 - 6.2.1
 │   │ └─project [03412277] log:
 │   │   ├─possible versions are: 0.0.0 or uninstalled
 │   │   └─project [03412277] is fixed to version 0.0.0
 │   └─restricted to versions 5.5.2 by an explicit requirement, leaving only versions: 5.5.2
 └─restricted by julia compatibility requirements to versions: 1.6.0 - 2.0.1 or uninstalled — no versions left

In [4]:
using DataFrames
using CSV
using Gadfly
using TextAnalysis
using MLJ
using Chain
using Pipe
using StableRNGs


[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0](cache misses: wrong source (1))
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0] (cache misses: wrong source (2))

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b](cache misses: wrong dep version loaded (1))

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up
[ Info: Precompiling CSV [336ed68f-0bac-5ca0-87d4-7b16caf5d00b] (cache misses: wrong dep version loaded (2))

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004] 

SYSTEM: caught exception of type :Me

LoadError: Failed to precompile Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004] to "/home/jzhang/.julia/compiled/v1.12/Gadfly/jl_zipEQD".


SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up


In [6]:
#import kagglehub
#path = kagglehub.dataset_download("team-ai/spam-text-message-classification")
#print("Path to dataset files: ", path)

df = CSV.read("/home/jzhang/1TB/Keylontic_Teachings/Anuhazi_Decode/SPAM_text_message_Data.csv", DataFrames.DataFrame)
first(df, 10) |> pretty


LoadError: UndefVarError: `pretty` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [6]:
df = @chain df begin
    DataFrames.transform(:Message =>ByRow(x -> StringDocument(x)) => :Message2)
end

Row,Category,Message,Message2
,String7,String,StringDo…
1,ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",A StringDocument{String}
2,ham,Ok lar... Joking wif u oni...,A StringDocument{String}
3,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,A StringDocument{String}
4,ham,U dun say so early hor... U c already then say...,A StringDocument{String}
5,ham,"Nah I don't think he goes to usf, he lives around here though",A StringDocument{String}
6,spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",A StringDocument{String}
7,ham,Even my brother is not like to speak with me. They treat me like aids patent.,A StringDocument{String}
8,ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,A StringDocument{String}
9,spam,WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,A StringDocument{String}


In [7]:
remove_case!.(df[:, :Message2])
prepare!.(df[:, :Message2], strip_html_tags | strip_punctuation| strip_numbers)
stem!.(df[:, :Message2])

5572-element Vector{Nothing}:
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 ⋮
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing
 nothing

In [8]:
crps = Corpus(df[:, :Message2])

A Corpus with 5572 documents:
 * 5572 StringDocument's
 * 0 FileDocument's
 * 0 TokenDocument's
 * 0 NGramDocument's

Corpus's lexicon contains 0 tokens
Corpus's index contains 0 tokens

In [9]:
update_lexicon!(crps)

In [10]:
m = DocumentTermMatrix(crps)
tfidf_mat = tf_idf(m)

5572×7298 SparseArrays.SparseMatrixCSC{Float64, Int64} with 75698 stored entries:
⎡⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎤
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎣⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠁⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⎦

In [11]:
dtm(m)

5572×7298 SparseArrays.SparseMatrixCSC{Int64, Int64} with 75698 stored entries:
⎡⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎤
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎢⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⎥
⎣⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠁⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⎦

In [12]:
X, y = tfidf_mat, df[:, :Category]


(sparse([43, 2279, 2851, 2872, 2934, 3958, 5069, 5083, 415, 734  …  1974, 2027, 2573, 2793, 3841, 3972, 4031, 4100, 4140, 4421], [1, 1, 1, 1, 1, 1, 1, 1, 2, 2  …  7298, 7298, 7298, 7298, 7298, 7298, 7298, 7298, 7298, 7298], [0.23378813547213786, 0.2517718382007639, 0.4514529512565421, 0.4514529512565421, 0.9697878212177571, 0.40912923707624127, 0.40912923707624127, 0.7792937849071262, 1.4478429947559612, 0.38101131440946345  …  0.19088577850959632, 0.4226756524141061, 1.0759016606904521, 0.2191651531036106, 0.31144521756828875, 0.23669836535189945, 0.7396823917246858, 0.5917459133797486, 0.3287477296554159, 0.2572808319042385], 5572, 7298), String7["ham", "ham", "spam", "ham", "ham", "spam", "ham", "ham", "spam", "spam"  …  "ham", "ham", "ham", "ham", "spam", "spam", "ham", "ham", "ham", "ham"])

In [83]:
#Pkg.rm("PyCall")
import MLJDecisionTreeInterface

In [24]:
#Pkg.add("MLJDecisionTreeInterface")

   Resolving package versions...
  No Changes to `~/MyAI/Project.toml`
  No Changes to `~/MyAI/Manifest.toml`


In [13]:
DecisionTreeClassifier = @load DecisionTreeClassifier pkg=DecisionTree
tree_model = DecisionTreeClassifier()

[ Info: For silent loading, specify `verbosity=0`. 


import MLJDecisionTreeInterface ✔


DecisionTreeClassifier(
  max_depth = -1, 
  min_samples_leaf = 1, 
  min_samples_split = 2, 
  min_purity_increase = 0.0, 
  n_subfeatures = 0, 
  post_prune = false, 
  merge_purity_threshold = 1.0, 
  display_depth = 5, 
  feature_importance = :impurity, 
  rng = Random.TaskLocalRNG())

In [19]:
evaluate(tree_model, X, y, 
                resampling=CV(shuffle=true),
                measures=[log_loss, accuracy],
                verbosity=0)

┌ Warning: The number and/or types of data arguments do not match what the specified model
│ supports. Suppress this type check by specifying `scitype_check_level=0`.
│ 
│ Run `@doc DecisionTree.DecisionTreeClassifier` to learn more about your model's requirements.
│ 
│ Commonly, but non exclusively, supervised models are constructed using the syntax
│ `machine(model, X, y)` or `machine(model, X, y, w)` while most other models are
│ constructed with `machine(model, X)`.  Here `X` are features, `y` a target, and `w`
│ sample or class weights.
│ 
│ In general, data in `machine(model, data...)` is expected to satisfy
│ 
│     scitype(data) <: MLJ.fit_data_scitype(model)
│ 
│ In the present case:
│ 
│ scitype(data) = Tuple{AbstractMatrix{Continuous}, AbstractVector{Textual}}
│ 
│ fit_data_scitype(model) = Tuple{Table{<:Union{AbstractVector{<:Continuous}, AbstractVector{<:Count}, AbstractVector{<:OrderedFactor}}}, AbstractVector{<:Finite}}
└ @ MLJBase ~/.julia/packages/MLJBase/v5sA7/src/mac

LoadError: ArgumentError: 
observation scitype of target = `Textual` but (LogLoss(tol = 2.22045e-16)) only supports `Union{Missing, Infinite, Finite}`.
To override measure checks, set check_measure=false. 

In [21]:
#tree = machine(tree_model, coerce(X, Continuous), coerce(y, Multiclass))
tree = machine(tree_model, X, y)

┌ Warning: The number and/or types of data arguments do not match what the specified model
│ supports. Suppress this type check by specifying `scitype_check_level=0`.
│ 
│ Run `@doc DecisionTree.DecisionTreeClassifier` to learn more about your model's requirements.
│ 
│ Commonly, but non exclusively, supervised models are constructed using the syntax
│ `machine(model, X, y)` or `machine(model, X, y, w)` while most other models are
│ constructed with `machine(model, X)`.  Here `X` are features, `y` a target, and `w`
│ sample or class weights.
│ 
│ In general, data in `machine(model, data...)` is expected to satisfy
│ 
│     scitype(data) <: MLJ.fit_data_scitype(model)
│ 
│ In the present case:
│ 
│ scitype(data) = Tuple{AbstractMatrix{Continuous}, AbstractVector{Textual}}
│ 
│ fit_data_scitype(model) = Tuple{Table{<:Union{AbstractVector{<:Continuous}, AbstractVector{<:Count}, AbstractVector{<:OrderedFactor}}}, AbstractVector{<:Finite}}
└ @ MLJBase ~/.julia/packages/MLJBase/v5sA7/src/mac

untrained Machine; caches model-specific representations of data
  model: DecisionTreeClassifier(max_depth = -1, …)
  args: 
    1:	Source @481 ⏎ AbstractMatrix{Continuous}
    2:	Source @011 ⏎ AbstractVector{Textual}


In [79]:
@doc DecisionTree.DecisionTreeClassifier

LoadError: UndefVarError: `DecisionTree` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: DecisionTree is loaded but not imported in the active module Main.

In [86]:
@doc DecisionTree.DecisionTreeClassifier

LoadError: UndefVarError: `DecisionTree` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Hint: DecisionTree is loaded but not imported in the active module Main.

In [22]:
rng = StableRNG(42)
train, test = partition(eachindex(y), 0.85, shuffle=true, rng=rng)

([3780, 3263, 1491, 1048, 1668, 1259, 3547, 2517, 4294, 1665  …  5527, 3382, 2561, 4734, 2954, 71, 803, 934, 1705, 1476], [3389, 785, 164, 2282, 1325, 859, 2646, 2696, 5353, 201  …  1201, 2472, 2483, 1126, 438, 2145, 1585, 1857, 5561, 4754])

In [23]:
MLJ.fit!(tree , rows=train)

LoadError: ArgumentError: a 'SparseArrays.SparseMatrixCSC{Float64, Int64}' is not a table; see `?Tables.table` for ways to treat an AbstractVecOrMat as a table

In [35]:
?Tables.table


!!! warning
    The following bindings may be internal; they may change or be removed in future versions:

      * `Tables.table`


```
Tables.table(m::AbstractVecOrMat; [header])
```

Wrap an `AbstractVecOrMat` (`Matrix`, `Vector`, `Adjoint`, etc.) in a `MatrixTable`, which satisfies the Tables.jl interface.  (An `AbstractVector` is treated as a 1-column matrix.) This allows accessing the matrix via `Tables.rows` and `Tables.columns`. An optional keyword argument iterator `header` can be passed which will be converted to a `Vector{Symbol}` to be used as the column names. Note that no copy of the `AbstractVecOrMat` is made.


In [49]:
yhat = MLJ.predict(tree, coerce(X[test, :], Continuous))

#To calculate the log-loss or binary cross entropy of our classification algorithm
println("Log-Loss on the Test Set : $(log_loss(yhat, coerce(y[test], Multiclass)) |> mean)")

#To calculate the accuracy of our classification algorithm
println("Accuracy on the Test Set: $(accuracy(mode.(yhat), coerce(y[test], Multiclass)))")

#To generate the Confusion Matrix of our Classification algorithm
ConfusionMatrix()(mode.(yhat), coerce(y[test], Multiclass))


LoadError: machine(DecisionTreeClassifier(max_depth = -1, …), …) has not been trained. 

In [25]:
using MLJ
iris = load_iris();
selectrows(iris, 1:3) |> pretty

┌──────────────┬─────────────┬──────────────┬─────────────┬──────────────────────────────────┐
│ sepal_length │ sepal_width │ petal_length │ petal_width │ target                           │
│ Float64      │ Float64     │ Float64      │ Float64     │ CategoricalValue{String, UInt32} │
│ Continuous   │ Continuous  │ Continuous   │ Continuous  │ Multiclass{3}                    │
├──────────────┼─────────────┼──────────────┼─────────────┼──────────────────────────────────┤
│ 5.1          │ 3.5         │ 1.4          │ 0.2         │ setosa                           │
│ 4.9          │ 3.0         │ 1.4          │ 0.2         │ setosa                           │
│ 4.7          │ 3.2         │ 1.3          │ 0.2         │ setosa                           │
└──────────────┴─────────────┴──────────────┴─────────────┴──────────────────────────────────┘


In [26]:
schema(iris)

┌──────────────┬───────────────┬──────────────────────────────────┐
│ names        │ scitypes      │ types                            │
├──────────────┼───────────────┼──────────────────────────────────┤
│ sepal_length │ Continuous    │ Float64                          │
│ sepal_width  │ Continuous    │ Float64                          │
│ petal_length │ Continuous    │ Float64                          │
│ petal_width  │ Continuous    │ Float64                          │
│ target       │ Multiclass{3} │ CategoricalValue{String, UInt32} │
└──────────────┴───────────────┴──────────────────────────────────┘


In [27]:
import DataFrames
iris = DataFrames.DataFrame(iris);

In [28]:
y, X = unpack(iris, ==(:target); rng=123);

In [29]:
first(X, 3) |> pretty

┌──────────────┬─────────────┬──────────────┬─────────────┐
│ sepal_length │ sepal_width │ petal_length │ petal_width │
│ Float64      │ Float64     │ Float64      │ Float64     │
│ Continuous   │ Continuous  │ Continuous   │ Continuous  │
├──────────────┼─────────────┼──────────────┼─────────────┤
│ 6.5          │ 2.8         │ 4.6          │ 1.5         │
│ 5.1          │ 3.5         │ 1.4          │ 0.2         │
│ 6.3          │ 3.3         │ 4.7          │ 1.6         │
└──────────────┴─────────────┴──────────────┴─────────────┘


In [30]:
models(matching(X, y))

54-element Vector{NamedTuple{(:name, :package_name, :is_supervised, :abstract_type, :constructor, :deep_properties, :docstring, :fit_data_scitype, :human_name, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :inverse_transform_scitype, :is_pure_julia, :is_wrapper, :iteration_parameter, :load_path, :package_license, :package_url, :package_uuid, :predict_scitype, :prediction_type, :reporting_operations, :reports_feature_importances, :supports_class_weights, :supports_online, :supports_training_losses, :supports_weights, :target_in_fit, :transform_scitype, :input_scitype, :target_scitype, :output_scitype)}}:
 (name = AdaBoostClassifier, package_name = MLJScikitLearnInterface, ... )
 (name = AdaBoostStumpClassifier, package_name = DecisionTree, ... )
 (name = BaggingClassifier, package_name = MLJScikitLearnInterface, ... )
 (name = BayesianLDA, package_name = MLJScikitLearnInterface, ... )
 (name = BayesianLDA, package_name = MultivariateStats, ... )


In [31]:
doc("DecisionTreeClassifier", pkg="DecisionTree")

```
DecisionTreeClassifier
```

A model type for constructing a CART decision tree classifier, based on [DecisionTree.jl](https://github.com/bensadeghi/DecisionTree.jl), and implementing the MLJ model interface.

From MLJ, the type can be imported using

```
DecisionTreeClassifier = @load DecisionTreeClassifier pkg=DecisionTree
```

Do `model = DecisionTreeClassifier()` to construct an instance with default hyper-parameters. Provide keyword arguments to override hyper-parameter defaults, as in `DecisionTreeClassifier(max_depth=...)`.

`DecisionTreeClassifier` implements the [CART algorithm](https://en.wikipedia.org/wiki/Decision_tree_learning), originally published in Breiman, Leo; Friedman, J. H.; Olshen, R. A.; Stone, C. J. (1984): "Classification and regression trees". *Monterey, CA: Wadsworth & Brooks/Cole Advanced Books & Software.*.

# Training data

In MLJ or MLJBase, bind an instance `model` to data with

```
mach = machine(model, X, y)
```

where

  * `X`: any table of input features (eg, a `DataFrame`) whose columns each have one of the following element scitypes: `Continuous`, `Count`, or `<:OrderedFactor`; check column scitypes with `schema(X)`
  * `y`: is the target, which can be any `AbstractVector` whose element scitype is `<:OrderedFactor` or `<:Multiclass`; check the scitype with `scitype(y)`

Train the machine using `fit!(mach, rows=...)`.

# Hyperparameters

  * `max_depth=-1`:          max depth of the decision tree (-1=any)
  * `min_samples_leaf=1`:    max number of samples each leaf needs to have
  * `min_samples_split=2`:   min number of samples needed for a split
  * `min_purity_increase=0`: min purity needed for a split
  * `n_subfeatures=0`: number of features to select at random (0 for all)
  * `post_prune=false`:      set to `true` for post-fit pruning
  * `merge_purity_threshold=1.0`: (post-pruning) merge leaves having                          combined purity `>= merge_purity_threshold`
  * `display_depth=5`:       max depth to show when displaying the tree
  * `feature_importance`: method to use for computing feature importances. One of `(:impurity, :split)`
  * `rng=Random.GLOBAL_RNG`: random number generator or seed

# Operations

  * `predict(mach, Xnew)`: return predictions of the target given features `Xnew` having the same scitype as `X` above. Predictions are probabilistic, but uncalibrated.
  * `predict_mode(mach, Xnew)`: instead return the mode of each prediction above.

# Fitted parameters

The fields of `fitted_params(mach)` are:

  * `raw_tree`: the raw `Node`, `Leaf` or `Root` object returned by the core DecisionTree.jl algorithm
  * `tree`: a visualizable, wrapped version of `raw_tree` implementing the AbstractTrees.jl interface; see "Examples" below
  * `encoding`: dictionary of target classes keyed on integers used internally by DecisionTree.jl
  * `features`: the names of the features encountered in training, in an order consistent with the output of `print_tree` (see below)

# Report

The fields of `report(mach)` are:

  * `classes_seen`: list of target classes actually observed in training
  * `print_tree`: alternative method to print the fitted tree, with single argument the tree depth; interpretation requires internal integer-class encoding (see "Fitted parameters" above).
  * `features`: the names of the features encountered in training, in an order consistent with the output of `print_tree` (see below)

# Accessor functions

  * `feature_importances(mach)` returns a vector of `(feature::Symbol => importance)` pairs; the type of importance is determined by the hyperparameter `feature_importance` (see above)

# Examples

```
using MLJ
DecisionTreeClassifier = @load DecisionTreeClassifier pkg=DecisionTree
model = DecisionTreeClassifier(max_depth=3, min_samples_split=3)

X, y = @load_iris
mach = machine(model, X, y) |> fit!

Xnew = (sepal_length = [6.4, 7.2, 7.4],
        sepal_width = [2.8, 3.0, 2.8],
        petal_length = [5.6, 5.8, 6.1],
        petal_width = [2.1, 1.6, 1.9],)
yhat = predict(mach, Xnew) # probabilistic predictions
predict_mode(mach, Xnew)   # point predictions
pdf.(yhat, "virginica")    # probabilities for the "verginica" class

julia> tree = fitted_params(mach).tree
petal_length < 2.45
├─ setosa (50/50)
└─ petal_width < 1.75
   ├─ petal_length < 4.95
   │  ├─ versicolor (47/48)
   │  └─ virginica (4/6)
   └─ petal_length < 4.85
      ├─ virginica (2/3)
      └─ virginica (43/43)

using Plots, TreeRecipe
plot(tree) # for a graphical representation of the tree

feature_importances(mach)
```

See also [DecisionTree.jl](https://github.com/bensadeghi/DecisionTree.jl) and the unwrapped model type [`MLJDecisionTreeInterface.DecisionTree.DecisionTreeClassifier`](@ref).


In [32]:
Tree = @load DecisionTreeClassifier pkg=DecisionTree

import MLJDecisionTreeInterface ✔


[ Info: For silent loading, specify `verbosity=0`. 


MLJDecisionTreeInterface.DecisionTreeClassifier

In [33]:
tree = Tree()

DecisionTreeClassifier(
  max_depth = -1, 
  min_samples_leaf = 1, 
  min_samples_split = 2, 
  min_purity_increase = 0.0, 
  n_subfeatures = 0, 
  post_prune = false, 
  merge_purity_threshold = 1.0, 
  display_depth = 5, 
  feature_importance = :impurity, 
  rng = Random.TaskLocalRNG())

In [34]:
evaluate(tree, X, y, resampling=CV(shuffle=true),
                measures=[log_loss, accuracy],
                verbosity=0)

PerformanceEvaluation object with these fields:
  model, measure, operation,
  measurement, per_fold, per_observation,
  fitted_params_per_fold, report_per_fold,
  train_test_rows, resampling, repeats
Extract:
┌───┬──────────────────────┬──────────────┬─────────────┐
│   │ measure              │ operation    │ measurement │
├───┼──────────────────────┼──────────────┼─────────────┤
│ A │ LogLoss(             │ predict      │ 1.92        │
│   │   tol = 2.22045e-16) │              │             │
│ B │ Accuracy()           │ predict_mode │ 0.947       │
└───┴──────────────────────┴──────────────┴─────────────┘
┌───┬──────────────────────────────────────────────────────┬─────────┐
│   │ per_fold                                             │ 1.96*SE │
├───┼──────────────────────────────────────────────────────┼─────────┤
│ A │ [2.22e-16, 2.22e-16, 2.22e-16, 7.21, 4.33, 2.22e-16] │ 2.73    │
│ B │ [1.0, 1.0, 1.0, 0.8, 0.88, 1.0]                      │ 0.0757  │
└───┴────────────────────────

In [35]:
typeof(y)

CategoricalVector{String, UInt32, String, CategoricalValue{String, UInt32}, Union{}} (alias for CategoricalArrays.CategoricalArray{String, 1, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}})

In [36]:
target_scitype(tree)

AbstractVector{<:Finite} (alias for AbstractArray{<:Finite, 1})

In [38]:
subtypes(Finite)

2-element Vector{Any}:
 Multiclass
 OrderedFactor

In [39]:
scitype(y)

AbstractVector{Multiclass{3}} (alias for AbstractArray{Multiclass{3}, 1})

In [40]:
yint = int.(y);

In [41]:
scitype(yint)

AbstractVector{Count} (alias for AbstractArray{Count, 1})

In [42]:
mach = machine(tree, X, y)

untrained Machine; caches model-specific representations of data
  model: DecisionTreeClassifier(max_depth = -1, …)
  args: 
    1:	Source @414 ⏎ Table{AbstractVector{Continuous}}
    2:	Source @025 ⏎ AbstractVector{Multiclass{3}}


In [43]:
train, test = partition(eachindex(y), 0.7);

In [46]:
using MLJ;
MLJ.fit!(mach, rows=train);

[ Info: Training machine(DecisionTreeClassifier(max_depth = -1, …), …).


In [48]:
yhat = MLJ.predict(mach, X[test, :]);

In [49]:
yhat[3:5]

3-element CategoricalDistributions.UnivariateFiniteVector{Multiclass{3}, String, UInt32, Float64}:
 UnivariateFinite{Multiclass{3}}(setosa=>1.0, versicolor=>0.0, virginica=>0.0)
 UnivariateFinite{Multiclass{3}}(setosa=>1.0, versicolor=>0.0, virginica=>0.0)
 UnivariateFinite{Multiclass{3}}(setosa=>0.0, versicolor=>1.0, virginica=>0.0)

In [50]:
log_loss(yhat, y[test])

1.6019401506274291

In [51]:
cross_entropy(yhat, y[test])

1.6019401506274291

In [52]:
measures()

LittleDict{Any, Any, Vector{Any}, Vector{Any}} with 55 entries:
  LPLoss                    => (aliases = ("l1", "l2", "mae", "mav", "mean_abso…
  MultitargetLPLoss         => (aliases = ("multitarget_l1", "multitarget_l2", …
  LPSumLoss                 => (aliases = ("l1_sum", "l2_sum"), consumes_multip…
  MultitargetLPSumLoss      => (aliases = ("multitarget_l1_sum", "multitarget_l…
  RootMeanSquaredError      => (aliases = ("rms", "rmse", "root_mean_squared_er…
  MultitargetRootMeanSquar… => (aliases = ("multitarget_rms", "multitarget_rmse…
  RootMeanSquaredLogError   => (aliases = ("rmsl", "rmsle", "root_mean_squared_…
  MultitargetRootMeanSquar… => (aliases = ("multitarget_rmsl", "multitarget_rms…
  RootMeanSquaredLogPropor… => (aliases = ("rmslp1",), consumes_multiple_observ…
  MultitargetRootMeanSquar… => (aliases = ("multitarget_rmslp1",), consumes_mul…
  RootMeanSquaredProportio… => (aliases = ("rmsp",), consumes_multiple_observat…
  MultitargetRootMeanSquar… => (aliases = ("m

In [54]:
MLJ.broadcast(pdf, yhat[3:5]), "virginica") #predicted probabilities of virginica

LoadError: MethodError: no method matching pdf(::UnivariateFinite{Multiclass{3}, String, UInt32, Float64})
The function `pdf` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  pdf(::UnivariateFinite, ::Missing)
   @ CategoricalDistributions ~/.julia/packages/CategoricalDistributions/g0UnN/src/methods.jl:165
  pdf(::UnivariateFinite{S, V, R, P}, ::Any) where {S, V, R, P}
   @ CategoricalDistributions ~/.julia/packages/CategoricalDistributions/g0UnN/src/methods.jl:167
  pdf(::Distributions.Kolmogorov, ::Real)
   @ Distributions ~/.julia/packages/Distributions/YQSrn/src/univariate/continuous/kolmogorov.jl:80
  ...


In [55]:
MLJ.broadcast(pdf, yhat, y[test])[3:5] #predicted probability of observed class

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [56]:
MLJ.mode.(yhat[3:5])

3-element CategoricalArrays.CategoricalArray{String,1,UInt32}:
 "setosa"
 "setosa"
 "versicolor"

In [57]:
MLJ.predict_mode(mach, X[test[3:5], :])

3-element CategoricalArrays.CategoricalArray{String,1,UInt32}:
 "setosa"
 "setosa"
 "versicolor"

In [58]:
L = levels(y)

3-element Vector{String}:
 "setosa"
 "versicolor"
 "virginica"

In [60]:
pdf(yhat[3:6], L)

4×3 Matrix{Float64}:
 1.0  0.0  0.0
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [61]:
v = Float64[1, 2, 3, 4]

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [62]:
stand = Standardizer()

Standardizer(
  features = Symbol[], 
  ignore = false, 
  ordered_factor = false, 
  count = false)

In [63]:
mach2 = machine(stand, v)

untrained Machine; caches model-specific representations of data
  model: Standardizer(features = Symbol[], …)
  args: 
    1:	Source @561 ⏎ AbstractVector{Continuous}


In [65]:
MLJ.fit!(mach2)

[ Info: Training machine(Standardizer(features = Symbol[], …), …).


trained Machine; caches model-specific representations of data
  model: Standardizer(features = Symbol[], …)
  args: 
    1:	Source @561 ⏎ AbstractVector{Continuous}


In [67]:
w = MLJ.transform(mach2, v)

4-element Vector{Float64}:
 -1.161895003862225
 -0.3872983346207417
  0.3872983346207417
  1.161895003862225

In [68]:
inverse_transform(mach2, w)

4-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0

In [70]:
evaluate!(mach, resampling=Holdout(fraction_train=0.7),
                       measures=[log_loss, accuracy],
                       verbosity=0)

PerformanceEvaluation object with these fields:
  model, measure, operation,
  measurement, per_fold, per_observation,
  fitted_params_per_fold, report_per_fold,
  train_test_rows, resampling, repeats
Extract:
┌───┬──────────────────────┬──────────────┬─────────────┐
│   │ measure              │ operation    │ measurement │
├───┼──────────────────────┼──────────────┼─────────────┤
│ A │ LogLoss(             │ predict      │ 1.6         │
│   │   tol = 2.22045e-16) │              │             │
│ B │ Accuracy()           │ predict_mode │ 0.956       │
└───┴──────────────────────┴──────────────┴─────────────┘


In [71]:
tree.max_depth = 3;
evaluate!(mach, resampling=Holdout(fraction_train=0.7),
                 measures=[log_loss, accuracy],
                 verbosity=0)

PerformanceEvaluation object with these fields:
  model, measure, operation,
  measurement, per_fold, per_observation,
  fitted_params_per_fold, report_per_fold,
  train_test_rows, resampling, repeats
Extract:
┌───┬──────────────────────┬──────────────┬─────────────┐
│   │ measure              │ operation    │ measurement │
├───┼──────────────────────┼──────────────┼─────────────┤
│ A │ LogLoss(             │ predict      │ 0.101       │
│   │   tol = 2.22045e-16) │              │             │
│ B │ Accuracy()           │ predict_mode │ 0.956       │
└───┴──────────────────────┴──────────────┴─────────────┘


In [73]:
Pkg.add("Flux")

   Resolving package versions...
  No Changes to `~/MyAI/Project.toml`
  No Changes to `~/MyAI/Manifest.toml`
